#
POST http://localhost:8081/transaction/
Content-Type: application/json

{
"description":"xisto",
"value": 100,
"category": "xisto",
"year": 2020,
"month": 5,
"day": 5,
"yearMonth": "2020-05"
"yearMonthDay": "2020-05-05"
"type": "-"


}
###





DELETE http://localhost:8081/transaction/5f58324205385597b67466a3

###
PUT http://localhost:8081/transaction/5f58324205385597b67466a3
Content-Type: application/json

{

"value": 700

}
###
get http://localhost:8081/transaction/yearMonth/2019-01

###
get http://localhost:8081/transaction/year/2020

###
get http://localhost:8081/transaction/

###